In [1]:
import numpy as np
import pandas as pd

# 결과 불러오기

In [8]:
df = pd.read_pickle("Base_Data.pkl")

In [9]:
df

Symbol             A005930                                            \
Symbol Name           삼성전자
                    총자산(원)        총자본(원)        총부채(원)        자본금(원)
year quarter
2000 3        2.496436e+13  1.401328e+13  1.095108e+13  8.776211e+11
     6        2.510607e+13  1.476346e+13  1.034261e+13  8.804522e+11
     9        2.613602e+13  1.592160e+13  1.021442e+13  8.816347e+11
     12       2.689505e+13  1.619285e+13  1.070220e+13  8.816751e+11
2001 3        2.783778e+13  1.768363e+13  1.015415e+13  8.816751e+11
...                    ...           ...           ...           ...
2021 12       2.511122e+14  1.931937e+14  5.791845e+13  8.975140e+11
2022 3        2.593540e+14  1.982758e+14  6.107824e+13  8.975140e+11
     6        2.589713e+14  2.039144e+14  5.505685e+13  8.975140e+11
     9        2.610291e+14  2.070457e+14  5.398337e+13  8.975140e+11
     12                NaN           NaN           NaN           NaN

Symbol                                                                \
Symbol Name
                   유동부채(원)      비유동부채(원)     *총차입부채(원)     *순차입부채(원)
year quarter
2000 3        6.627064e+12  4.324011e+12  5.377145e+12  4.123370e+12
     6        6.277503e+12  4.065104e+12  4.866135e+12  3.124732e+12
     9        6.601534e+12  3.612889e+12  4.575874e+12  1.684689e+12
     12       8.608449e+12  2.093751e+12  4.061056e+12  1.446021e+12
2001 3        8.129206e+12  2.024941e+12  4.349802e+12  1.931723e+12
...                    ...           ...           ...           ...
2021 12       5.306730e+13  4.851149e+12  9.804559e+12 -9.114889e+12
2022 3        5.679978e+13  4.278465e+12  1.082537e+13 -1.110678e+13
     6        5.031086e+13  4.745989e+12  9.068400e+12 -7.114918e+12
     9        4.884874e+13  5.134628e+12  4.793840e+12 -4.475861e+12
     12                NaN           NaN           NaN           NaN

Symbol                                    ...  A900080 A900090 A900130  \
Symbol Name                               ... 에스앤씨엔진그룹  차이나하오란    웨이포트
                   유동자산(원)      비유동자산(원)  ...  코스닥 대형주 코스닥 대형주 코스닥 대형주
year quarter                              ...
2000 3        6.745764e+12  1.821859e+13  ...      NaN     NaN     NaN
     6        6.696682e+12  1.840938e+13  ...      NaN     NaN     NaN
     9        7.908331e+12  1.822769e+13  ...      NaN     NaN     NaN
     12       7.756441e+12  1.913861e+13  ...      NaN     NaN     NaN
2001 3        7.260043e+12  2.057774e+13  ...      NaN     NaN     NaN
...                    ...           ...  ...      ...     ...     ...
2021 12       7.355342e+13  1.775588e+14  ...     None    None    None
2022 3        8.146603e+13  1.778880e+14  ...     None    None    None
     6        7.619448e+13  1.827768e+14  ...     None    None    None
     9        7.395366e+13  1.870754e+14  ...     None    None    None
     12                NaN           NaN  ...     None    None    None

Symbol       A900150 A900180  A950010 A950030 A950070 A950100 A950180
Symbol Name   성융광전투자      완리 평산차업 KDR  네프로아이티    중국고섬  SBI모기지     SNK
             코스닥 대형주 코스닥 대형주  코스닥 대형주 코스닥 대형주 코스닥 대형주 코스닥 대형주 코스닥 대형주
year quarter
2000 3           NaN     NaN      NaN     NaN     NaN     NaN     NaN
     6           NaN     NaN      NaN     NaN     NaN     NaN     NaN
     9           NaN     NaN      NaN     NaN     NaN     NaN     NaN
     12          NaN     NaN      NaN     NaN     NaN     NaN     NaN
2001 3           NaN     NaN      NaN     NaN     NaN     NaN     NaN
...              ...     ...      ...     ...     ...     ...     ...
2021 12         None    None     None    None    None    None       N
2022 3          None    None     None    None    None    None       N
     6          None    None     None    None    None    None       N
     9          None    None     None    None    None    None    None
     12         None    None     None    None    None    None    None

[92 rows x 203232 columns]

# 이렇게 Slicing

In [3]:
df.loc[:, (slice(None), '삼성전자', slice(None))]

Symbol             A005930                                            \
Symbol Name           삼성전자
                    총자산(원)        총자본(원)        총부채(원)        자본금(원)
year quarter
2000 3        2.496436e+13  1.401328e+13  1.095108e+13  8.776211e+11
     6        2.510607e+13  1.476346e+13  1.034261e+13  8.804522e+11
     9        2.613602e+13  1.592160e+13  1.021442e+13  8.816347e+11
     12       2.689505e+13  1.619285e+13  1.070220e+13  8.816751e+11
2001 3        2.783778e+13  1.768363e+13  1.015415e+13  8.816751e+11
...                    ...           ...           ...           ...
2021 12       2.511122e+14  1.931937e+14  5.791845e+13  8.975140e+11
2022 3        2.593540e+14  1.982758e+14  6.107824e+13  8.975140e+11
     6        2.589713e+14  2.039144e+14  5.505685e+13  8.975140e+11
     9        2.610291e+14  2.070457e+14  5.398337e+13  8.975140e+11
     12                NaN           NaN           NaN           NaN

Symbol                                                                \
Symbol Name
                   유동부채(원)      비유동부채(원)     *총차입부채(원)     *순차입부채(원)
year quarter
2000 3        6.627064e+12  4.324011e+12  5.377145e+12  4.123370e+12
     6        6.277503e+12  4.065104e+12  4.866135e+12  3.124732e+12
     9        6.601534e+12  3.612889e+12  4.575874e+12  1.684689e+12
     12       8.608449e+12  2.093751e+12  4.061056e+12  1.446021e+12
2001 3        8.129206e+12  2.024941e+12  4.349802e+12  1.931723e+12
...                    ...           ...           ...           ...
2021 12       5.306730e+13  4.851149e+12  9.804559e+12 -9.114889e+12
2022 3        5.679978e+13  4.278465e+12  1.082537e+13 -1.110678e+13
     6        5.031086e+13  4.745989e+12  9.068400e+12 -7.114918e+12
     9        4.884874e+13  5.134628e+12  4.793840e+12 -4.475861e+12
     12                NaN           NaN           NaN           NaN

Symbol                                    ...                                \
Symbol Name                               ...
                   유동자산(원)      비유동자산(원)  ...       거래대금(원) 상장및상장예정주식수(보통주)
year quarter                              ...
2000 3        6.745764e+12  1.821859e+13  ...           NaN             NaN
     6        6.696682e+12  1.840938e+13  ...  2.611347e+11    1.509012e+08
     9        7.908331e+12  1.822769e+13  ...  2.317735e+11    1.512319e+08
     12       7.756441e+12  1.913861e+13  ...  1.942091e+11    1.512399e+08
2001 3        7.260043e+12  2.057774e+13  ...  1.238044e+11    1.512399e+08
...                    ...           ...  ...           ...             ...
2021 12       7.355342e+13  1.775588e+14  ...  1.120743e+12    5.969783e+09
2022 3        8.146603e+13  1.778880e+14  ...  8.732126e+11    5.969783e+09
     6        7.619448e+13  1.827768e+14  ...  1.082799e+12    5.969783e+09
     9        7.395366e+13  1.870754e+14  ...  1.187344e+12    5.969783e+09
     12                NaN           NaN  ...  1.218355e+12    5.969783e+09

Symbol                                                                   \
Symbol Name
             상장및상장예정주식수(우선주) 순매수대금(기관계)(원) 순매수대금(외국인계)(원)  순매수대금(개인)(원)
year quarter
2000 3                   NaN           NaN            NaN           NaN
     6            23893427.0 -1.684060e+10  -6.732003e+10  7.705425e+10
     9            23893427.0 -7.367350e+09  -2.369369e+10  2.769976e+10
     12           23893427.0 -2.384329e+10   7.884840e+09 -1.177294e+10
2001 3            23893427.0 -1.008720e+09  -9.226480e+09  1.119503e+10
...                      ...           ...            ...           ...
2021 12          822886700.0 -2.355468e+11   4.711275e+10  1.868082e+11
2022 3           822886700.0  1.186300e+08  -2.243323e+11  2.201073e+11
     6           822886700.0 -5.676019e+10  -1.709717e+11  2.288256e+11
     9           822886700.0  3.001964e+10   6.857518e+10 -9.878368e+10
     12          822886700.0 -1.378300e+11   3.427397e+11 -1.881547e+11

Symbol
Symbol Name
                잔고금액 융자(원)    잔고금액 대주(원) KOSPI 200 편입여부 코스닥 대형주
year quarter
2000 3                 NaN           NaN            NaN     NaN
     6                 NaN           NaN              Y       N
     9                 NaN           NaN              Y       N
     12                NaN           NaN              Y       N
2001 3                 NaN           NaN              Y       N
...                    ...           ...            ...     ...
2021 12       5.407110e+11  1.931000e+09              Y       N
2022 3        6.275740e+11  6.870000e+08              Y       N
     6        6.815550e+11  4.390000e+08              Y       N
     9        6.351040e+11  2.100000e+08              Y       N
     12       4.508710e+11  1.424000e+09              Y       N

[92 rows x 58 columns]

# 티커명이 바뀐 경우가 있음

In [4]:
df.loc[:, (slice(None), '삼성물산', slice(None))].columns.get_level_values('Symbol').unique()

Index(['A028260', 'A000830'], dtype='object', name='Symbol')

In [5]:
overlap = df.loc[:, (slice(None), '삼성물산', slice(None))].columns.get_level_values('Symbol').unique()

In [6]:
df.loc[:, (overlap[0], '삼성물산', slice(None))]

Symbol             A028260                                            \
Symbol Name           삼성물산
                    총자산(원)        총자본(원)        총부채(원)        자본금(원)
year quarter
2000 3        1.207817e+12  4.080010e+11  7.998160e+11  1.250000e+10
     6        1.494903e+12  6.782232e+11  8.166794e+11  1.250000e+10
     9        1.504570e+12  7.063610e+11  7.982090e+11  1.250000e+10
     12       1.478252e+12  6.723749e+11  8.058776e+11  1.250000e+10
2001 3        1.835511e+12  6.746820e+11  1.160828e+12  1.250000e+10
...                    ...           ...           ...           ...
2021 12       4.418092e+13  2.840802e+13  1.577289e+13  1.885145e+10
2022 3        4.209578e+13  2.622764e+13  1.586814e+13  1.885145e+10
     6        3.967385e+13  2.355446e+13  1.611939e+13  1.885145e+10
     9        3.876493e+13  2.298044e+13  1.578449e+13  1.885145e+10
     12                NaN           NaN           NaN           NaN

Symbol                                                                \
Symbol Name
                   유동부채(원)      비유동부채(원)     *총차입부채(원)     *순차입부채(원)
year quarter
2000 3        3.322850e+11  4.675310e+11  4.088130e+11  3.982560e+11
     6        3.440972e+11  4.725821e+11  3.721298e+11  3.605396e+11
     9        3.282640e+11  4.699450e+11  3.653600e+11  3.545340e+11
     12       2.103882e+11  5.954894e+11  3.788700e+11  3.694799e+11
2001 3        2.367250e+11  9.241030e+11  4.813750e+11  4.702280e+11
...                    ...           ...           ...           ...
2021 12       7.967519e+12  7.805374e+12  1.476917e+12 -1.871699e+12
2022 3        8.805868e+12  7.062271e+12  1.552334e+12  6.740992e+10
     6        9.435099e+12  6.684287e+12  4.082768e+12  1.541842e+12
     9        8.979476e+12  6.805009e+12  3.613264e+12  6.098554e+11
     12                NaN           NaN           NaN           NaN

Symbol                                    ...                                \
Symbol Name                               ...
                   유동자산(원)      비유동자산(원)  ...       거래대금(원) 상장및상장예정주식수(보통주)
year quarter                              ...
2000 3        1.853950e+11  1.022422e+12  ...           NaN             NaN
     6        1.393024e+11  1.355600e+12  ...           NaN             0.0
     9        1.730880e+11  1.331482e+12  ...           NaN             0.0
     12       1.188120e+11  1.359441e+12  ...           NaN             0.0
2001 3        1.016060e+11  1.733905e+12  ...           NaN             0.0
...                    ...           ...  ...           ...             ...
2021 12       8.502681e+12  3.567824e+13  ...  9.265365e+10     186887081.0
2022 3        9.146876e+12  3.294890e+13  ...  2.655521e+10     186887081.0
     6        8.698201e+12  3.097565e+13  ...  1.075746e+11     186887081.0
     9        9.215916e+12  2.954901e+13  ...  3.387402e+10     186887081.0
     12                NaN           NaN  ...  3.920259e+10     186887081.0

Symbol                                                                   \
Symbol Name
             상장및상장예정주식수(우선주) 순매수대금(기관계)(원) 순매수대금(외국인계)(원)  순매수대금(개인)(원)
year quarter
2000 3                   NaN           NaN            NaN           NaN
     6                   0.0           NaN            NaN           NaN
     9                   0.0           NaN            NaN           NaN
     12                  0.0           NaN            NaN           NaN
2001 3                   0.0           NaN            NaN           NaN
...                      ...           ...            ...           ...
2021 12            1627425.0  5.508830e+09   1.562785e+10 -2.123653e+10
2022 3             1627425.0  6.183300e+08   2.954310e+09 -3.534980e+09
     6             1627425.0  2.399922e+10   5.161260e+09 -2.930572e+10
     9             1627425.0 -8.484900e+08  -2.761130e+09  3.612840e+09
     12            1627425.0 -4.949690e+09   1.157070e+10 -6.229750e+09

Symbol
Symbol Name
                잔고금액 융자(원)   잔고금액 대주(원) KOSPI 200 편입여부 코스닥 대형주
year quarter
2000 3                 NaN          NaN            NaN     NaN
     6                 NaN          NaN            NaN     NaN
     9                 NaN          NaN            NaN     NaN
     12                NaN          NaN            NaN     NaN
2001 3                 NaN          NaN            NaN     NaN
...                    ...          ...            ...     ...
2021 12       5.749500e+10   14000000.0              Y       N
2022 3        5.113900e+10    9000000.0              Y       N
     6        3.932300e+10   10000000.0              Y       N
     9        3.841300e+10    2000000.0              Y       N
     12       3.601100e+10  110000000.0              Y       N

[92 rows x 58 columns]

In [7]:
df.loc[:, (overlap[1], '삼성물산', slice(None))]

Symbol             A000830                                            \
Symbol Name           삼성물산
                    총자산(원)        총자본(원)        총부채(원)        자본금(원)
year quarter
2000 3        8.913979e+12  3.569736e+12  5.344243e+12  8.004210e+11
     6        8.960416e+12  3.726638e+12  5.233778e+12  8.004209e+11
     9        7.738923e+12  2.697067e+12  5.041856e+12  8.004210e+11
     12       7.321044e+12  2.512359e+12  4.808685e+12  8.004209e+11
2001 3        7.695971e+12  2.855981e+12  4.839990e+12  8.004209e+11
...                    ...           ...           ...           ...
2021 12                NaN           NaN           NaN           NaN
2022 3                 NaN           NaN           NaN           NaN
     6                 NaN           NaN           NaN           NaN
     9                 NaN           NaN           NaN           NaN
     12                NaN           NaN           NaN           NaN

Symbol                                                                \
Symbol Name
                   유동부채(원)      비유동부채(원)     *총차입부채(원)     *순차입부채(원)
year quarter
2000 3        3.597486e+12  1.746757e+12  2.964768e+12  2.588727e+12
     6        3.227194e+12  2.006585e+12  2.664184e+12  2.374190e+12
     9        3.411786e+12  1.630070e+12  2.813868e+12  2.173775e+12
     12       3.656899e+12  1.151786e+12  2.193294e+12  1.662472e+12
2001 3        3.678726e+12  1.161264e+12  2.212152e+12  1.752318e+12
...                    ...           ...           ...           ...
2021 12                NaN           NaN           NaN           NaN
2022 3                 NaN           NaN           NaN           NaN
     6                 NaN           NaN           NaN           NaN
     9                 NaN           NaN           NaN           NaN
     12                NaN           NaN           NaN           NaN

Symbol                                    ...                                \
Symbol Name                               ...
                   유동자산(원)      비유동자산(원)  ...       거래대금(원) 상장및상장예정주식수(보통주)
year quarter                              ...
2000 3        3.949023e+12  4.964956e+12  ...           NaN             NaN
     6        3.746336e+12  5.214080e+12  ...  1.615603e+10             0.0
     9        3.590855e+12  4.148068e+12  ...  1.100860e+10             0.0
     12       3.459565e+12  3.861479e+12  ...  6.385499e+09             0.0
2001 3        3.523578e+12  4.172394e+12  ...  4.796702e+09             0.0
...                    ...           ...  ...           ...             ...
2021 12                NaN           NaN  ...           NaN             0.0
2022 3                 NaN           NaN  ...           NaN             0.0
     6                 NaN           NaN  ...           NaN             0.0
     9                 NaN           NaN  ...           NaN             0.0
     12                NaN           NaN  ...           NaN             0.0

Symbol                                                                   \
Symbol Name
             상장및상장예정주식수(우선주) 순매수대금(기관계)(원) 순매수대금(외국인계)(원)  순매수대금(개인)(원)
year quarter
2000 3                   NaN           NaN            NaN           NaN
     6                   0.0  2.024610e+09    684760000.0 -3.293880e+09
     9                   0.0  4.285800e+08     -1280000.0 -4.930000e+08
     12                  0.0 -5.217500e+08    187610000.0  1.315670e+09
2001 3                   0.0 -5.841200e+08      2580000.0  5.573600e+08
...                      ...           ...            ...           ...
2021 12                  0.0           NaN            NaN           NaN
2022 3                   0.0           NaN            NaN           NaN
     6                   0.0           NaN            NaN           NaN
     9                   0.0           NaN            NaN           NaN
     12                  0.0           NaN            NaN           NaN

Symbol
Symbol Name
             잔고금액 융자(원) 잔고금액 대주(원) KOSPI 200 편입여부 코스닥 대형주
year quarter
2000 3              NaN        NaN            NaN     NaN
     6              NaN        NaN              Y       N
     9              NaN        NaN              Y       N
     12             NaN        NaN              Y       N
2001 3              NaN        NaN              Y       N
...                 ...        ...            ...     ...
2021 12             NaN        NaN           None    None
2022 3              NaN        NaN           None    None
     6              NaN        NaN           None    None
     9              NaN        NaN           None    None
     12             NaN        NaN           None    None

[92 rows x 58 columns]