In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
path = os.getcwd() + '/Data/korea/'
file_list = os.listdir(path)

In [3]:
file_list

['산업분류_유동주식비율_관리종목_monthly.pkl',
 '수정시고저종,종가,시총,거래대금_daily.pkl',
 '개인외국인기관수급_daily.pkl',
 '분기재무데이터_연결.pkl',
 '경제지표_daily.pkl',
 '신용융자_지수편입종목_daily.pkl',
 '분기재무데이터_별도.pkl',
 '인덱스_daily.pkl']

In [46]:
'''for 0 '''
#df = pd.read_pickle(path + file_list[0])
#df.loc[:,(slice(None), slice(None), '삼성전자')]
'''for 1 '''
#df = pd.read_pickle(path + file_list[1])
#df.loc[:,(slice(None), slice(None), '삼성전자')]
'''for 2 '''
# feature, 심볼, 종목명
#df = pd.read_pickle(path + file_list[2])
#df.loc[:,(slice(None), slice(None), '삼성전자')]
'''for 3'''
# (심볼, 이름) 쿼터별 데이터, 
# df = pd.read_pickle(path + file_list[3])
# df.T.loc[:, (slice(None), '삼성전자')].T
'''for 4'''
# 시장 데이터 >> 얘는 모든 칼럼 공통임
# df = pd.read_pickle(path + file_list[4])
# df
'''for 5'''
# 잔고, 편입, 대형주
# df = pd.read_pickle(path + file_list[5])
# df.loc[:, (slice(None), slice(None), '삼성전자')]

'''for 7'''
# 시장 데이터 >> 얘도 모든 칼럼 공통
# df = pd.read_pickle(path + file_list[7])

'for 7'

In [268]:
df = pd.read_pickle(path + file_list[7])
df.columns.swaplevel(1,0)
#df.T.loc[:, (slice(None), '삼성전자')].T

MultiIndex([(           'MKF2000', '종가지수(포인트)'),
            (           'MKF2000', '시가지수(포인트)'),
            (           'MKF2000', '고가지수(포인트)'),
            (           'MKF2000', '저가지수(포인트)'),
            (           'MKF2000',   '거래대금(원)'),
            (               '코스피', '종가지수(포인트)'),
            (               '코스피', '시가지수(포인트)'),
            (               '코스피', '고가지수(포인트)'),
            (               '코스피', '저가지수(포인트)'),
            (               '코스피',   '거래대금(원)'),
            (      '코스피 200 동일가중', '종가지수(포인트)'),
            (      '코스피 200 동일가중', '시가지수(포인트)'),
            (      '코스피 200 동일가중', '고가지수(포인트)'),
            (      '코스피 200 동일가중', '저가지수(포인트)'),
            (      '코스피 200 동일가중',   '거래대금(원)'),
            (           '코스피 200', '종가지수(포인트)'),
            (           '코스피 200', '시가지수(포인트)'),
            (           '코스피 200', '고가지수(포인트)'),
            (           '코스피 200', '저가지수(포인트)'),
            (           '코스피 200',   '거래대금(원)'),
            (               '코스닥', '종가지수(포인트)'),
            (               '코스닥', '시가지수(포인트)'),
            (               '코스닥', '고가지수(포인트)'),
            (               '코스닥', '저가지수(포인트)'),
            (               '코스닥',   '거래대금(원)'),
            (           '코스닥 150', '종가지수(포인트)'),
            (           '코스닥 150', '시가지수(포인트)'),
            (           '코스닥 150', '고가지수(포인트)'),
            (           '코스닥 150', '저가지수(포인트)'),
            (           '코스닥 150',   '거래대금(원)'),
            (      '코스닥 150 동일가중', '종가지수(포인트)'),
            (      '코스닥 150 동일가중', '시가지수(포인트)'),
            (      '코스닥 150 동일가중', '고가지수(포인트)'),
            (      '코스닥 150 동일가중', '저가지수(포인트)'),
            (      '코스닥 150 동일가중',   '거래대금(원)'),
            (        '엔선물 레버리지지수', '종가지수(포인트)'),
            (        '엔선물 레버리지지수', '시가지수(포인트)'),
            (        '엔선물 레버리지지수', '고가지수(포인트)'),
            (        '엔선물 레버리지지수', '저가지수(포인트)'),
            (        '엔선물 레버리지지수',   '거래대금(원)'),
            (       '미국달러선물 레버리지', '종가지수(포인트)'),
            (       '미국달러선물 레버리지', '시가지수(포인트)'),
            (       '미국달러선물 레버리지', '고가지수(포인트)'),
            (       '미국달러선물 레버리지', '저가지수(포인트)'),
            (       '미국달러선물 레버리지',   '거래대금(원)'),
            (          '미국달러선물지수', '종가지수(포인트)'),
            (          '미국달러선물지수', '시가지수(포인트)'),
            (          '미국달러선물지수', '고가지수(포인트)'),
            (          '미국달러선물지수', '저가지수(포인트)'),
            (          '미국달러선물지수',   '거래대금(원)'),
            (            '엔선물 지수', '종가지수(포인트)'),
            (            '엔선물 지수', '시가지수(포인트)'),
            (            '엔선물 지수', '고가지수(포인트)'),
            (            '엔선물 지수', '저가지수(포인트)'),
            (            '엔선물 지수',   '거래대금(원)'),
            (      '코스피 200 선물지수', '종가지수(포인트)'),
            (      '코스피 200 선물지수', '시가지수(포인트)'),
            (      '코스피 200 선물지수', '고가지수(포인트)'),
            (      '코스피 200 선물지수', '저가지수(포인트)'),
            (      '코스피 200 선물지수',   '거래대금(원)'),
            (        '코스닥 150 선물', '종가지수(포인트)'),
            (        '코스닥 150 선물', '시가지수(포인트)'),
            (        '코스닥 150 선물', '고가지수(포인트)'),
            (        '코스닥 150 선물', '저가지수(포인트)'),
            (        '코스닥 150 선물',   '거래대금(원)'),
            (      '코스닥 150 레버리지', '종가지수(포인트)'),
            (      '코스닥 150 레버리지', '시가지수(포인트)'),
            (      '코스닥 150 레버리지', '고가지수(포인트)'),
            (      '코스닥 150 레버리지', '저가지수(포인트)'),
            (      '코스닥 150 레버리지',   '거래대금(원)'),
            ( '코스피 200 선물 인버스 지수', '종가지수(포인트)'),
            ( '코스피 200 선물 인버스 지수', '시가지수(포인트)'),
            ( '코스피 200 선물 인버스 지수', '고가지수(포인트)'),
            ( '코스피 200 선물 인버스 지수', '저가지수(포인트)'),
            ( '코스피 200 선물 인버스 지수',   '거래대금(원)'),
            ('코스피 200 선물 레버리지 지수', '종가지수(포인트)'),
            ('코스피 200 선물 레버리지 지수', '시가지수(포인트)'),
            ('코스피 200 선물 레버리지 지수', '고가지수(포인트)'),
            ('코스피 200 선물 레버리지 지수', '저가지수(포인트)'),
            ('코스피 200 선물 레버리지 지수',   '거래대금(원)'),
            (    '코스닥 150 선물 인버스', '종가지수(포인트)'),
            (    '코스닥 150 선물 인버스', '시가지수(포인트)'),
            (    '코스닥 150 선물 인버스', '고가지수(포인트)'),
            (    '코스닥 150 선물 인버스', '저가지수(포인트)'),
            (    '코스닥 150 선물 인버스',   '거래대금(원)'),
            ( '코스피 200 선물 인버스-2X', '종가지수(포인트)'),
            ( '코스피 200 선물 인버스-2X', '시가지수(포인트)'),
            ( '코스피 200 선물 인버스-2X', '고가지수(포인트)'),
            ( '코스피 200 선물 인버스-2X', '저가지수(포인트)'),
            ( '코스피 200 선물 인버스-2X',   '거래대금(원)'),
            (           '나스닥 100', '종가지수(포인트)'),
            (           '나스닥 100', '시가지수(포인트)'),
            (           '나스닥 100', '고가지수(포인트)'),
            (           '나스닥 100', '저가지수(포인트)'),
            (           '나스닥 100',   '거래대금(원)'),
            (           'S&P 500', '종가지수(포인트)'),
            (           'S&P 500', '시가지수(포인트)'),
            (           'S&P 500', '고가지수(포인트)'),
            (           'S&P 500', '저가지수(포인트)'),
            (           'S&P 500',   '거래대금(원)')],
           names=['Symbol Name', 'Item Name'])

티커 이름들

In [199]:
df = pd.read_pickle(path + file_list[6])
df.columns = df.columns.swaplevel(0, 1).swaplevel(1,2)
df

year                         2000                                            \
quarter                        1Q            2Q            3Q            4Q
                           총자산(원)        총자산(원)        총자산(원)        총자산(원)
Symbol  Symbol Name
A005930 삼성전자         2.496436e+13  2.510607e+13  2.613602e+13  2.689505e+13
A373220 LG에너지솔루션              NaN           NaN           NaN           NaN
A207940 삼성바이오로직스              NaN           NaN           NaN           NaN
A000660 SK하이닉스       1.973483e+13  1.965479e+13  1.970803e+13  1.789985e+13
A051910 LG화학                  NaN           NaN           NaN           NaN
...                           ...           ...           ...           ...
A950010 평산차업 KDR              NaN           NaN           NaN           NaN
A950030 네프로아이티                NaN           NaN           NaN           NaN
A950070 중국고섬                  NaN           NaN           NaN           NaN
A950100 SBI모기지                NaN           NaN           NaN           NaN
A950180 SNK                   NaN           NaN           NaN           NaN

year                         2001                                            \
quarter                        1Q            2Q            3Q            4Q
                           총자산(원)        총자산(원)        총자산(원)        총자산(원)
Symbol  Symbol Name
A005930 삼성전자         2.783778e+13  2.745871e+13  2.764093e+13  2.791941e+13
A373220 LG에너지솔루션              NaN           NaN           NaN           NaN
A207940 삼성바이오로직스              NaN           NaN           NaN           NaN
A000660 SK하이닉스       1.680382e+13  1.677406e+13  1.577666e+13  1.200428e+13
A051910 LG화학         6.883727e+12  3.984962e+12  3.973516e+12  3.636326e+12
...                           ...           ...           ...           ...
A950010 평산차업 KDR              NaN           NaN           NaN           NaN
A950030 네프로아이티                NaN           NaN           NaN           NaN
A950070 중국고섬                  NaN           NaN           NaN           NaN
A950100 SBI모기지                NaN           NaN           NaN           NaN
A950180 SNK                   NaN           NaN           NaN           NaN

year                         2002                ...          2020  \
quarter                        1Q            2Q  ...            2Q
                           총자산(원)        총자산(원)  ...     종속기업투자(원)
Symbol  Symbol Name                              ...
A005930 삼성전자         2.959656e+13  3.163746e+13  ...  0.000000e+00
A373220 LG에너지솔루션              NaN           NaN  ...  0.000000e+00
A207940 삼성바이오로직스              NaN           NaN  ...  1.191400e+10
A000660 SK하이닉스       1.173435e+13  1.090365e+13  ...  5.730797e+12
A051910 LG화학         3.852789e+12  3.816024e+12  ...  5.405242e+12
...                           ...           ...  ...           ...
A950010 평산차업 KDR              NaN           NaN  ...  0.000000e+00
A950030 네프로아이티                NaN           NaN  ...  0.000000e+00
A950070 중국고섬                  NaN           NaN  ...  0.000000e+00
A950100 SBI모기지                NaN           NaN  ...  0.000000e+00
A950180 SNK                   NaN           NaN  ...  3.970168e+10

year                                                     2021                \
quarter                        3Q            4Q            1Q            2Q
                        종속기업투자(원)     종속기업투자(원)     종속기업투자(원)     종속기업투자(원)
Symbol  Symbol Name
A005930 삼성전자         0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
A373220 LG에너지솔루션     0.000000e+00  4.444021e+12  4.556731e+12  4.692638e+12
A207940 삼성바이오로직스     1.191400e+10  1.191400e+10  1.191400e+10  1.191400e+10
A000660 SK하이닉스       5.760168e+12  5.793470e+12  6.426502e+12  6.726502e+12
A051910 LG화학         6.215987e+12  8.793551e+12  8.792485e+12  8.869359e+12
...                           ...           ...           ...           ...
A950010 평산차업 KDR     0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
A950030 네프로아이티       0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
A950070 중국고섬         0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
A950100 SBI모기지       0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
A950180 SNK          4.276303e+10  4.185256e+10  4.127343e+10  3.926573e+10

year                                                     2022                \
quarter                        3Q            4Q            1Q            2Q
                        종속기업투자(원)     종속기업투자(원)     종속기업투자(원)     종속기업투자(원)
Symbol  Symbol Name
A005930 삼성전자         0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
A373220 LG에너지솔루션     4.808706e+12  5.255911e+12  5.732428e+12  6.736755e+12
A207940 삼성바이오로직스     1.191400e+10  1.191400e+10  1.191400e+10  3.272215e+12
A000660 SK하이닉스       1.061038e+13  1.068720e+13  1.182843e+13  1.342754e+13
A051910 LG화학         8.859696e+12  8.755113e+12  8.559935e+12  8.499639e+12
...                           ...           ...           ...           ...
A950010 평산차업 KDR     0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
A950030 네프로아이티       0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
A950070 중국고섬         0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
A950100 SBI모기지       0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
A950180 SNK          3.606412e+10  3.551352e+10  0.000000e+00  3.337995e+10

year
quarter                        3Q
                        종속기업투자(원)
Symbol  Symbol Name
A005930 삼성전자         0.000000e+00
A373220 LG에너지솔루션     7.058869e+12
A207940 삼성바이오로직스     3.277094e+12
A000660 SK하이닉스       1.371910e+13
A051910 LG화학         8.503047e+12
...                           ...
A950010 평산차업 KDR     0.000000e+00
A950030 네프로아이티       0.000000e+00
A950070 중국고섬         0.000000e+00
A950100 SBI모기지       0.000000e+00
A950180 SNK          2.830332e+10

[3504 rows x 3458 columns]

In [206]:
df = df.T.unstack(level=2)
df = df.T

In [209]:
datetime_index = []

for x in zip(df.columns.get_level_values('year'), df.columns.get_level_values('quarter')):

    if x[1] == '1Q':
        m = 3
    elif x[1] == '2Q':
        m = 6
    elif x[1] == '3Q':
        m = 9
    elif x[1] == '4Q':    
        m = 12

    date = dt.datetime(year=x[0], month=m, day=1)

    datetime_index.append(date.strftime('%Y-%m'))

In [210]:
datetime_index = pd.to_datetime(datetime_index)

In [211]:
df.T

Symbol             A005930                                            \
Symbol Name           삼성전자
                    총자산(원)        총자본(원)        총부채(원)        자본금(원)
year quarter
2000 1Q       2.496436e+13  1.401328e+13  1.095108e+13  8.776211e+11
     2Q       2.510607e+13  1.476346e+13  1.034261e+13  8.804522e+11
     3Q       2.613602e+13  1.592160e+13  1.021442e+13  8.816347e+11
     4Q       2.689505e+13  1.619285e+13  1.070220e+13  8.816751e+11
2001 1Q       2.783778e+13  1.768363e+13  1.015415e+13  8.816751e+11
...                    ...           ...           ...           ...
2021 3Q       2.406844e+14  1.873901e+14  5.329431e+13  8.975140e+11
     4Q       2.511122e+14  1.931937e+14  5.791845e+13  8.975140e+11
2022 1Q       2.593540e+14  1.982758e+14  6.107824e+13  8.975140e+11
     2Q       2.589713e+14  2.039144e+14  5.505685e+13  8.975140e+11
     3Q       2.610291e+14  2.070457e+14  5.398337e+13  8.975140e+11

Symbol                                                                \
Symbol Name
                   유동부채(원)      비유동부채(원)     *총차입부채(원)     *순차입부채(원)
year quarter
2000 1Q       6.627064e+12  4.324011e+12  5.377145e+12  4.123370e+12
     2Q       6.277503e+12  4.065104e+12  4.866135e+12  3.124732e+12
     3Q       6.601534e+12  3.612889e+12  4.575874e+12  1.684689e+12
     4Q       8.608449e+12  2.093751e+12  4.061056e+12  1.446021e+12
2001 1Q       8.129206e+12  2.024941e+12  4.349802e+12  1.931723e+12
...                    ...           ...           ...           ...
2021 3Q       4.959792e+13  3.696390e+12  1.122722e+13 -9.456243e+12
     4Q       5.306730e+13  4.851149e+12  9.804559e+12 -9.114889e+12
2022 1Q       5.679978e+13  4.278465e+12  1.082537e+13 -1.110678e+13
     2Q       5.031086e+13  4.745989e+12  9.068400e+12 -7.114918e+12
     3Q       4.884874e+13  5.134628e+12  4.793840e+12 -4.475861e+12

Symbol                                    ...         A950180                  \
Symbol Name                               ...             SNK
                   유동자산(원)      비유동자산(원)  ... 투자활동으로인한현금흐름(원) 재무활동으로인한현금흐름(원)
year quarter                              ...
2000 1Q       6.745764e+12  1.821859e+13  ...             NaN             NaN
     2Q       6.696682e+12  1.840938e+13  ...             NaN             NaN
     3Q       7.908331e+12  1.822769e+13  ...             NaN             NaN
     4Q       7.756441e+12  1.913861e+13  ...             NaN             NaN
2001 1Q       7.260043e+12  2.057774e+13  ...             NaN             NaN
...                    ...           ...  ...             ...             ...
2021 3Q       7.325302e+13  1.674314e+14  ...    5.935850e+08   -2.041009e+09
     4Q       7.355342e+13  1.775588e+14  ...   -1.027016e+10   -1.640520e+08
2022 1Q       8.146603e+13  1.778880e+14  ...    3.026510e+09   -2.492370e+08
     2Q       7.619448e+13  1.827768e+14  ...   -7.057940e+09   -3.492070e+08
     3Q       7.395366e+13  1.870754e+14  ...   -1.211350e+10   -3.761990e+08

Symbol                                                                    \
Symbol Name
             신종자본증권(원) 전환사채(원) 신주인수권부사채(원) 교환사채(원) 투자부동산(원) 유형자산감가상각비(원)
year quarter
2000 1Q            0.0     0.0         0.0     0.0      0.0          0.0
     2Q            0.0     0.0         0.0     0.0      0.0          0.0
     3Q            0.0     0.0         0.0     0.0      0.0          0.0
     4Q            0.0     0.0         0.0     0.0      0.0          0.0
2001 1Q            0.0     0.0         0.0     0.0      0.0          0.0
...                ...     ...         ...     ...      ...          ...
2021 3Q            0.0     0.0         0.0     0.0      0.0  174707000.0
     4Q            0.0     0.0         0.0     0.0      0.0  478937000.0
2022 1Q            0.0     0.0         0.0     0.0      0.0  548512000.0
     2Q            0.0     0.0         0.0     0.0      0.0  417958000.0
     3Q            0.0     0.0         0.0     0.0      0.0  537336000.0

Symbol
Symbol Name
             매각예정비유동자산(원)     종속기업투자(원)
year quarter
2000 1Q               0.0  0.000000e+00
     2Q               0.0  0.000000e+00
     3Q               0.0  0.000000e+00
     4Q               0.0  0.000000e+00
2001 1Q               0.0  0.000000e+00
...                   ...           ...
2021 3Q               0.0  3.606412e+10
     4Q               0.0  3.551352e+10
2022 1Q               0.0  0.000000e+00
     2Q               0.0  3.337995e+10
     3Q               0.0  2.830332e+10

[91 rows x 133152 columns]

In [217]:
df = df.T
df.index = pd.MultiIndex.from_arrays([datetime_index.year, datetime_index.month], names=['year', 'quarter'])

In [220]:
df.T

year                                      2000                              \
quarter                                     3             6             9
Symbol  Symbol Name
A005930 삼성전자        총자산(원)        2.496436e+13  2.510607e+13  2.613602e+13
                    총자본(원)        1.401328e+13  1.476346e+13  1.592160e+13
                    총부채(원)        1.095108e+13  1.034261e+13  1.021442e+13
                    자본금(원)        8.776211e+11  8.804522e+11  8.816347e+11
                    유동부채(원)       6.627064e+12  6.277503e+12  6.601534e+12
...                                        ...           ...           ...
A950180 SNK         교환사채(원)       0.000000e+00  0.000000e+00  0.000000e+00
                    투자부동산(원)      0.000000e+00  0.000000e+00  0.000000e+00
                    유형자산감가상각비(원)  0.000000e+00  0.000000e+00  0.000000e+00
                    매각예정비유동자산(원)  0.000000e+00  0.000000e+00  0.000000e+00
                    종속기업투자(원)     0.000000e+00  0.000000e+00  0.000000e+00

year                                                    2001                \
quarter                                     12            3             6
Symbol  Symbol Name
A005930 삼성전자        총자산(원)        2.689505e+13  2.783778e+13  2.745871e+13
                    총자본(원)        1.619285e+13  1.768363e+13  1.862370e+13
                    총부채(원)        1.070220e+13  1.015415e+13  8.835018e+12
                    자본금(원)        8.816751e+11  8.816751e+11  8.817225e+11
                    유동부채(원)       8.608449e+12  8.129206e+12  6.861242e+12
...                                        ...           ...           ...
A950180 SNK         교환사채(원)       0.000000e+00  0.000000e+00  0.000000e+00
                    투자부동산(원)      0.000000e+00  0.000000e+00  0.000000e+00
                    유형자산감가상각비(원)  0.000000e+00  0.000000e+00  0.000000e+00
                    매각예정비유동자산(원)  0.000000e+00  0.000000e+00  0.000000e+00
                    종속기업투자(원)     0.000000e+00  0.000000e+00  0.000000e+00

year                                                                  2002  \
quarter                                     9             12            3
Symbol  Symbol Name
A005930 삼성전자        총자산(원)        2.764093e+13  2.791941e+13  2.959656e+13
                    총자본(원)        1.889807e+13  1.947375e+13  2.173137e+13
                    총부채(원)        8.742860e+12  8.445657e+12  7.865192e+12
                    자본금(원)        8.821172e+11  8.821172e+11  8.848610e+11
                    유동부채(원)       6.656885e+12  6.314242e+12  6.021280e+12
...                                        ...           ...           ...
A950180 SNK         교환사채(원)       0.000000e+00  0.000000e+00  0.000000e+00
                    투자부동산(원)      0.000000e+00  0.000000e+00  0.000000e+00
                    유형자산감가상각비(원)  0.000000e+00  0.000000e+00  0.000000e+00
                    매각예정비유동자산(원)  0.000000e+00  0.000000e+00  0.000000e+00
                    종속기업투자(원)     0.000000e+00  0.000000e+00  0.000000e+00

year                                            ...          2020  \
quarter                                     6   ...            6
Symbol  Symbol Name                             ...
A005930 삼성전자        총자산(원)        3.163746e+13  ...  2.181974e+14
                    총자본(원)        2.269991e+13  ...  1.787504e+14
                    총부채(원)        8.937558e+12  ...  3.944696e+13
                    자본금(원)        8.865760e+11  ...  8.975140e+11
                    유동부채(원)       7.244966e+12  ...  3.721580e+13
...                                        ...  ...           ...
A950180 SNK         교환사채(원)       0.000000e+00  ...  0.000000e+00
                    투자부동산(원)      0.000000e+00  ...  0.000000e+00
                    유형자산감가상각비(원)  0.000000e+00  ...  2.575810e+08
                    매각예정비유동자산(원)  0.000000e+00  ...  0.000000e+00
                    종속기업투자(원)     0.000000e+00  ...  3.970168e+10

year                                                                  2021  \
quarter                                     9             12            3
Symbol  Symbol Name
A005930 삼성전자        총자산(원)        2.282869e+14  2.296644e+14  2.365306e+14
                    총자본(원)        1.815876e+14  1.833167e+14  1.747561e+14
                    총부채(원)        4.669924e+13  4.634770e+13  6.177450e+13
                    자본금(원)        8.975140e+11  8.975140e+11  8.975140e+11
                    유동부채(원)       4.464224e+13  4.441290e+13  5.993368e+13
...                                        ...           ...           ...
A950180 SNK         교환사채(원)       0.000000e+00  0.000000e+00  0.000000e+00
                    투자부동산(원)      0.000000e+00  0.000000e+00  0.000000e+00
                    유형자산감가상각비(원)  2.357160e+08  2.243940e+08  2.181080e+08
                    매각예정비유동자산(원)  0.000000e+00  0.000000e+00  0.000000e+00
                    종속기업투자(원)     4.276303e+10  4.185256e+10  4.127343e+10

year                                                                        \
quarter                                     6             9             12
Symbol  Symbol Name
A005930 삼성전자        총자산(원)        2.278276e+14  2.406844e+14  2.511122e+14
                    총자본(원)        1.813529e+14  1.873901e+14  1.931937e+14
                    총부채(원)        4.647471e+13  5.329431e+13  5.791845e+13
                    자본금(원)        8.975140e+11  8.975140e+11  8.975140e+11
                    유동부채(원)       4.275377e+13  4.959792e+13  5.306730e+13
...                                        ...           ...           ...
A950180 SNK         교환사채(원)       0.000000e+00  0.000000e+00  0.000000e+00
                    투자부동산(원)      0.000000e+00  0.000000e+00  0.000000e+00
                    유형자산감가상각비(원)  2.886090e+08  1.747070e+08  4.789370e+08
                    매각예정비유동자산(원)  0.000000e+00  0.000000e+00  0.000000e+00
                    종속기업투자(원)     3.926573e+10  3.606412e+10  3.551352e+10

year                                      2022
quarter                                     3             6             9
Symbol  Symbol Name
A005930 삼성전자        총자산(원)        2.593540e+14  2.589713e+14  2.610291e+14
                    총자본(원)        1.982758e+14  2.039144e+14  2.070457e+14
                    총부채(원)        6.107824e+13  5.505685e+13  5.398337e+13
                    자본금(원)        8.975140e+11  8.975140e+11  8.975140e+11
                    유동부채(원)       5.679978e+13  5.031086e+13  4.884874e+13
...                                        ...           ...           ...
A950180 SNK         교환사채(원)       0.000000e+00  0.000000e+00  0.000000e+00
                    투자부동산(원)      0.000000e+00  0.000000e+00  0.000000e+00
                    유형자산감가상각비(원)  5.485120e+08  4.179580e+08  5.373360e+08
                    매각예정비유동자산(원)  0.000000e+00  0.000000e+00  0.000000e+00
                    종속기업투자(원)     0.000000e+00  3.337995e+10  2.830332e+10

[133152 rows x 91 columns]

In [213]:
pd.MultiIndex.from_arrays([datetime_index.year, datetime_index.month], names=['year', 'quarter'])

MultiIndex([(2000,  3),
            (2000,  6),
            (2000,  9),
            (2000, 12),
            (2001,  3),
            (2001,  6),
            (2001,  9),
            (2001, 12),
            (2002,  3),
            (2002,  6),
            (2002,  9),
            (2002, 12),
            (2003,  3),
            (2003,  6),
            (2003,  9),
            (2003, 12),
            (2004,  3),
            (2004,  6),
            (2004,  9),
            (2004, 12),
            (2005,  3),
            (2005,  6),
            (2005,  9),
            (2005, 12),
            (2006,  3),
            (2006,  6),
            (2006,  9),
            (2006, 12),
            (2007,  3),
            (2007,  6),
            (2007,  9),
            (2007, 12),
            (2008,  3),
            (2008,  6),
            (2008,  9),
            (2008, 12),
            (2009,  3),
            (2009,  6),
            (2009,  9),
            (2009, 12),
            (2010,  3),
            (2010,  6),
            (2010,  9),
            (2010, 12),
            (2011,  3),
            (2011,  6),
            (2011,  9),
            (2011, 12),
            (2012,  3),
            (2012,  6),
            (2012,  9),
            (2012, 12),
            (2013,  3),
            (2013,  6),
            (2013,  9),
            (2013, 12),
            (2014,  3),
            (2014,  6),
            (2014,  9),
            (2014, 12),
            (2015,  3),
            (2015,  6),
            (2015,  9),
            (2015, 12),
            (2016,  3),
            (2016,  6),
            (2016,  9),
            (2016, 12),
            (2017,  3),
            (2017,  6),
            (2017,  9),
            (2017, 12),
            (2018,  3),
            (2018,  6),
            (2018,  9),
            (2018, 12),
            (2019,  3),
            (2019,  6),
            (2019,  9),
            (2019, 12),
            (2020,  3),
            (2020,  6),
            (2020,  9),
            (2020, 12),
            (2021,  3),
            (2021,  6),
            (2021,  9),
            (2021, 12),
            (2022,  3),
            (2022,  6),
            (2022,  9)],
           names=['year', 'quarter'])

In [78]:
new = []
for x in df.columns.get_level_values('quarter'):
    if x == '1Q':
        new.append('3')

Index(['1Q', '2Q', '3Q', '4Q', '1Q', '2Q', '3Q', '4Q', '1Q', '2Q',
       ...
       '2Q', '3Q', '4Q', '1Q', '2Q', '3Q', '4Q', '1Q', '2Q', '3Q'],
      dtype='object', name='quarter', length=3458)

In [79]:
df = pd.read_pickle(path + file_list[0])
ticker_name = list(df.columns.get_level_values('Symbol Name'))

0, 1, 2, 5 는 처리함

In [5]:
'''for 0 '''
df = pd.read_pickle(path + file_list[0])
'''for 1 '''
df2 = pd.read_pickle(path + file_list[1])
# '''for 2 '''
#feature, 심볼, 종목명
df3 = pd.read_pickle(path + file_list[2])
'''for 3'''
# 잔고, 편입, 대형주
df4 = pd.read_pickle(path + file_list[5])

df = pd.concat([df, df2, df3, df4], axis=1)
del df2, df3, df4

df

            FnGuide Industry Group                                             \
Symbol                     A005930  A373220   A207940 A000660 A051910 A006400
Symbol Name                   삼성전자 LG에너지솔루션  삼성바이오로직스  SK하이닉스    LG화학   삼성SDI
2000-05-31                     반도체      NaN       NaN     반도체     NaN    하드웨어
2000-06-01                     NaN      NaN       NaN     NaN     NaN     NaN
2000-06-02                     NaN      NaN       NaN     NaN     NaN     NaN
2000-06-05                     NaN      NaN       NaN     NaN     NaN     NaN
2000-06-07                     NaN      NaN       NaN     NaN     NaN     NaN
...                            ...      ...       ...     ...     ...     ...
2022-11-24                     NaN      NaN       NaN     NaN     NaN     NaN
2022-11-25                     NaN      NaN       NaN     NaN     NaN     NaN
2022-11-28                     NaN      NaN       NaN     NaN     NaN     NaN
2022-11-29                     NaN      NaN       NaN     NaN     NaN     NaN
2022-11-30                    하드웨어     하드웨어  제약 및 바이오     반도체      소재    하드웨어

                                                  ...  코스닥 대형주          \
Symbol        A005380 A035420   A000270  A005490  ...  A900080 A900090
Symbol Name       현대차   NAVER        기아 POSCO홀딩스  ... 에스앤씨엔진그룹  차이나하오란
2000-05-31   자동차 및 부품     NaN  자동차 및 부품       소재  ...      NaN     NaN
2000-06-01        NaN     NaN       NaN      NaN  ...      NaN     NaN
2000-06-02        NaN     NaN       NaN      NaN  ...      NaN     NaN
2000-06-05        NaN     NaN       NaN      NaN  ...      NaN     NaN
2000-06-07        NaN     NaN       NaN      NaN  ...      NaN     NaN
...               ...     ...       ...      ...  ...      ...     ...
2022-11-24        NaN     NaN       NaN      NaN  ...      NaN     NaN
2022-11-25        NaN     NaN       NaN      NaN  ...      NaN     NaN
2022-11-28        NaN     NaN       NaN      NaN  ...      NaN     NaN
2022-11-29        NaN     NaN       NaN      NaN  ...      NaN     NaN
2022-11-30   자동차 및 부품   소프트웨어  자동차 및 부품       소재  ...      NaN     NaN


Symbol      A900130 A900150 A900180  A950010 A950030 A950070 A950100 A950180
Symbol Name    웨이포트  성융광전투자      완리 평산차업 KDR  네프로아이티    중국고섬  SBI모기지     SNK
2000-05-31      NaN     NaN     NaN      NaN     NaN     NaN     NaN     NaN
2000-06-01      NaN     NaN     NaN      NaN     NaN     NaN     NaN     NaN
2000-06-02      NaN     NaN     NaN      NaN     NaN     NaN     NaN     NaN
2000-06-05      NaN     NaN     NaN      NaN     NaN     NaN     NaN     NaN
2000-06-07      NaN     NaN     NaN      NaN     NaN     NaN     NaN     NaN
...             ...     ...     ...      ...     ...     ...     ...     ...
2022-11-24      NaN     NaN     NaN      NaN     NaN     NaN     NaN     NaN
2022-11-25      NaN     NaN     NaN      NaN     NaN     NaN     NaN     NaN
2022-11-28      NaN     NaN     NaN      NaN     NaN     NaN     NaN     NaN
2022-11-29      NaN     NaN     NaN      NaN     NaN     NaN     NaN     NaN
2022-11-30      NaN     NaN     NaN      NaN     NaN     NaN     NaN     NaN

[5656 rows x 70080 columns]

In [32]:
df.to_pickle('semi_reg.pkl')

In [33]:
df = pd.read_pickle('semi_reg.pkl')

In [34]:
test = df.copy()

In [20]:
df.columns.levels[0]

Index(['FnGuide Industry Group', 'KOSPI 200 편입여부', '거래대금(원)', '거래소(시장)',
       '관리종목지정사유', '상장및상장예정주식수(보통주)', '상장및상장예정주식수(우선주)', '수정고가(원)', '수정시가(원)',
       '수정저가(원)', '수정주가(원)', '순매수대금(개인)(원)', '순매수대금(기관계)(원)', '순매수대금(외국인계)(원)',
       '시가총액 (상장예정주식수 포함)(원)', '유동주식비율(%)', '잔고금액 대주(원)', '잔고금액 융자(원)',
       '종가(원)', '코스닥 대형주'],
      dtype='object')

In [28]:
df.columns

MultiIndex([('FnGuide Industry Group', 'A005930',     '삼성전자'),
            ('FnGuide Industry Group', 'A373220', 'LG에너지솔루션'),
            ('FnGuide Industry Group', 'A207940', '삼성바이오로직스'),
            ('FnGuide Industry Group', 'A000660',   'SK하이닉스'),
            ('FnGuide Industry Group', 'A051910',     'LG화학'),
            ('FnGuide Industry Group', 'A006400',    '삼성SDI'),
            ('FnGuide Industry Group', 'A005380',      '현대차'),
            ('FnGuide Industry Group', 'A035420',    'NAVER'),
            ('FnGuide Industry Group', 'A000270',       '기아'),
            ('FnGuide Industry Group', 'A005490', 'POSCO홀딩스'),
            ...
            (               '코스닥 대형주', 'A900080', '에스앤씨엔진그룹'),
            (               '코스닥 대형주', 'A900090',   '차이나하오란'),
            (               '코스닥 대형주', 'A900130',     '웨이포트'),
            (               '코스닥 대형주', 'A900150',   '성융광전투자'),
            (               '코스닥 대형주', 'A900180',       '완리'),
            (               '코스닥 대형주', 'A950010', '평산차업 KDR'),
            (               '코스닥 대형주', 'A950030',   '네프로아이티'),
            (               '코스닥 대형주', 'A950070',     '중국고섬'),
            (               '코스닥 대형주', 'A950100',   'SBI모기지'),
            (               '코스닥 대형주', 'A950180',      'SNK')],
           names=[None, 'Symbol', 'Symbol Name'], length=70080)

In [35]:
test.columns = df.columns.swaplevel(0, 2)

In [57]:
test2 = test.resample('Q').last()

In [63]:
test2.index = pd.MultiIndex.from_arrays([test2.index.year, test2.index.month], names=['year', 'quarter'])

AttributeError: 'MultiIndex' object has no attribute 'year'

In [65]:
test2.columns = test2.columns.swaplevel(0,1)

꼴 만들었다 아래

In [221]:
test2.to_pickle('semi_reg.pkl')

In [223]:
test2

Symbol                      A005930                A373220  \
Symbol Name                    삼성전자               LG에너지솔루션
             FnGuide Industry Group FnGuide Industry Group
year quarter
2000 6                          반도체                   하드웨어
     9                          반도체                   하드웨어
     12                         반도체                   하드웨어
2001 3                          반도체                   하드웨어
     6                          반도체                   하드웨어
...                             ...                    ...
2021 12                        하드웨어                   하드웨어
2022 3                         하드웨어                   하드웨어
     6                         하드웨어                   하드웨어
     9                         하드웨어                   하드웨어
     12                        하드웨어                   하드웨어

Symbol                      A207940                A000660  \
Symbol Name                삼성바이오로직스                 SK하이닉스
             FnGuide Industry Group FnGuide Industry Group
year quarter
2000 6                     제약 및 바이오                    반도체
     9                     제약 및 바이오                    반도체
     12                    제약 및 바이오                    반도체
2001 3                     제약 및 바이오                    반도체
     6                     제약 및 바이오                    반도체
...                             ...                    ...
2021 12                    제약 및 바이오                    반도체
2022 3                     제약 및 바이오                    반도체
     6                     제약 및 바이오                    반도체
     9                     제약 및 바이오                    반도체
     12                    제약 및 바이오                    반도체

Symbol                      A051910                A006400  \
Symbol Name                    LG화학                  삼성SDI
             FnGuide Industry Group FnGuide Industry Group
year quarter
2000 6                           소재                   하드웨어
     9                           소재                   하드웨어
     12                          소재                   하드웨어
2001 3                           소재                   하드웨어
     6                           소재                   하드웨어
...                             ...                    ...
2021 12                          소재                   하드웨어
2022 3                           소재                   하드웨어
     6                           소재                   하드웨어
     9                           소재                   하드웨어
     12                          소재                   하드웨어

Symbol                      A005380                A035420  \
Symbol Name                     현대차                  NAVER
             FnGuide Industry Group FnGuide Industry Group
year quarter
2000 6                     자동차 및 부품                  소프트웨어
     9                     자동차 및 부품                  소프트웨어
     12                    자동차 및 부품                  소프트웨어
2001 3                     자동차 및 부품                  소프트웨어
     6                     자동차 및 부품                  소프트웨어
...                             ...                    ...
2021 12                    자동차 및 부품                  소프트웨어
2022 3                     자동차 및 부품                  소프트웨어
     6                     자동차 및 부품                  소프트웨어
     9                     자동차 및 부품                  소프트웨어
     12                    자동차 및 부품                  소프트웨어

Symbol                      A000270                A005490  ...  A900080  \
Symbol Name                      기아               POSCO홀딩스  ... 에스앤씨엔진그룹
             FnGuide Industry Group FnGuide Industry Group  ...  코스닥 대형주
year quarter                                                ...
2000 6                     자동차 및 부품                     소재  ...     None
     9                     자동차 및 부품                     소재  ...     None
     12                    자동차 및 부품                     소재  ...     None
2001 3                     자동차 및 부품                     소재  ...     None
     6                     자동차 및 부품                     소재  ...     None
...                             ...                    ...  ...      ...
2021 12                    자동차 및 부품                     소재  ...     None
2022 3                     자동차 및 부품                     소재  ...     None
     6                     자동차 및 부품                     소재  ...     None
     9                     자동차 및 부품                     소재  ...     None
     12                    자동차 및 부품                     소재  ...     None

Symbol       A900090 A900130 A900150 A900180  A950010 A950030 A950070 A950100  \
Symbol Name   차이나하오란    웨이포트  성융광전투자      완리 평산차업 KDR  네프로아이티    중국고섬  SBI모기지
             코스닥 대형주 코스닥 대형주 코스닥 대형주 코스닥 대형주  코스닥 대형주 코스닥 대형주 코스닥 대형주 코스닥 대형주
year quarter
2000 6          None    None    None    None     None    None    None    None
     9          None    None    None    None     None    None    None    None
     12         None    None    None    None     None    None    None    None
2001 3          None    None    None    None     None    None    None    None
     6          None    None    None    None     None    None    None    None
...              ...     ...     ...     ...      ...     ...     ...     ...
2021 12         None    None    None    None     None    None    None    None
2022 3          None    None    None    None     None    None    None    None
     6          None    None    None    None     None    None    None    None
     9          None    None    None    None     None    None    None    None
     12         None    None    None    None     None    None    None    None

Symbol       A950180
Symbol Name      SNK
             코스닥 대형주
year quarter
2000 6          None
     9          None
     12         None
2001 3          None
     6          None
...              ...
2021 12            N
2022 3             N
     6             N
     9          None
     12         None

[91 rows x 70080 columns]

In [26]:
df.loc[:, ('KOSPI 200 편입여부', slice(None), slice(None))]

            KOSPI 200 편입여부                                                    \
Symbol             A005930  A373220  A207940 A000660 A051910 A006400 A005380
Symbol Name           삼성전자 LG에너지솔루션 삼성바이오로직스  SK하이닉스    LG화학   삼성SDI     현대차
2000-05-31               Y      NaN      NaN       Y     NaN       Y       Y
2000-06-01               Y      NaN      NaN       Y     NaN       Y       Y
2000-06-02               Y      NaN      NaN       Y     NaN       Y       Y
2000-06-05               Y      NaN      NaN       Y     NaN       Y       Y
2000-06-07               Y      NaN      NaN       Y     NaN       Y       Y
...                    ...      ...      ...     ...     ...     ...     ...
2022-11-24               Y        Y        Y       Y       Y       Y       Y
2022-11-25               Y        Y        Y       Y       Y       Y       Y
2022-11-28               Y        Y        Y       Y       Y       Y       Y
2022-11-29               Y        Y        Y       Y       Y       Y       Y
2022-11-30               Y        Y        Y       Y       Y       Y       Y

                                      ...                                   \
Symbol      A035420 A000270  A005490  ...  A900080 A900090 A900130 A900150
Symbol Name   NAVER      기아 POSCO홀딩스  ... 에스앤씨엔진그룹  차이나하오란    웨이포트  성융광전투자
2000-05-31      NaN       N        Y  ...      NaN     NaN     NaN     NaN
2000-06-01      NaN       N        Y  ...      NaN     NaN     NaN     NaN
2000-06-02      NaN       N        Y  ...      NaN     NaN     NaN     NaN
2000-06-05      NaN       N        Y  ...      NaN     NaN     NaN     NaN
2000-06-07      NaN       N        Y  ...      NaN     NaN     NaN     NaN
...             ...     ...      ...  ...      ...     ...     ...     ...
2022-11-24        Y       Y        Y  ...      NaN     NaN     NaN     NaN
2022-11-25        Y       Y        Y  ...      NaN     NaN     NaN     NaN
2022-11-28        Y       Y        Y  ...      NaN     NaN     NaN     NaN
2022-11-29        Y       Y        Y  ...      NaN     NaN     NaN     NaN
2022-11-30        Y       Y        Y  ...      NaN     NaN     NaN     NaN


Symbol      A900180  A950010 A950030 A950070 A950100 A950180
Symbol Name      완리 평산차업 KDR  네프로아이티    중국고섬  SBI모기지     SNK
2000-05-31      NaN      NaN     NaN     NaN     NaN     NaN
2000-06-01      NaN      NaN     NaN     NaN     NaN     NaN
2000-06-02      NaN      NaN     NaN     NaN     NaN     NaN
2000-06-05      NaN      NaN     NaN     NaN     NaN     NaN
2000-06-07      NaN      NaN     NaN     NaN     NaN     NaN
...             ...      ...     ...     ...     ...     ...
2022-11-24      NaN      NaN     NaN     NaN     NaN     NaN
2022-11-25      NaN      NaN     NaN     NaN     NaN     NaN
2022-11-28      NaN      NaN     NaN     NaN     NaN     NaN
2022-11-29      NaN      NaN     NaN     NaN     NaN     NaN
2022-11-30      NaN      NaN     NaN     NaN     NaN     NaN

[5656 rows x 3504 columns]

In [224]:
test2

Symbol                      A005930                A373220  \
Symbol Name                    삼성전자               LG에너지솔루션
             FnGuide Industry Group FnGuide Industry Group
year quarter
2000 6                          반도체                   하드웨어
     9                          반도체                   하드웨어
     12                         반도체                   하드웨어
2001 3                          반도체                   하드웨어
     6                          반도체                   하드웨어
...                             ...                    ...
2021 12                        하드웨어                   하드웨어
2022 3                         하드웨어                   하드웨어
     6                         하드웨어                   하드웨어
     9                         하드웨어                   하드웨어
     12                        하드웨어                   하드웨어

Symbol                      A207940                A000660  \
Symbol Name                삼성바이오로직스                 SK하이닉스
             FnGuide Industry Group FnGuide Industry Group
year quarter
2000 6                     제약 및 바이오                    반도체
     9                     제약 및 바이오                    반도체
     12                    제약 및 바이오                    반도체
2001 3                     제약 및 바이오                    반도체
     6                     제약 및 바이오                    반도체
...                             ...                    ...
2021 12                    제약 및 바이오                    반도체
2022 3                     제약 및 바이오                    반도체
     6                     제약 및 바이오                    반도체
     9                     제약 및 바이오                    반도체
     12                    제약 및 바이오                    반도체

Symbol                      A051910                A006400  \
Symbol Name                    LG화학                  삼성SDI
             FnGuide Industry Group FnGuide Industry Group
year quarter
2000 6                           소재                   하드웨어
     9                           소재                   하드웨어
     12                          소재                   하드웨어
2001 3                           소재                   하드웨어
     6                           소재                   하드웨어
...                             ...                    ...
2021 12                          소재                   하드웨어
2022 3                           소재                   하드웨어
     6                           소재                   하드웨어
     9                           소재                   하드웨어
     12                          소재                   하드웨어

Symbol                      A005380                A035420  \
Symbol Name                     현대차                  NAVER
             FnGuide Industry Group FnGuide Industry Group
year quarter
2000 6                     자동차 및 부품                  소프트웨어
     9                     자동차 및 부품                  소프트웨어
     12                    자동차 및 부품                  소프트웨어
2001 3                     자동차 및 부품                  소프트웨어
     6                     자동차 및 부품                  소프트웨어
...                             ...                    ...
2021 12                    자동차 및 부품                  소프트웨어
2022 3                     자동차 및 부품                  소프트웨어
     6                     자동차 및 부품                  소프트웨어
     9                     자동차 및 부품                  소프트웨어
     12                    자동차 및 부품                  소프트웨어

Symbol                      A000270                A005490  ...  A900080  \
Symbol Name                      기아               POSCO홀딩스  ... 에스앤씨엔진그룹
             FnGuide Industry Group FnGuide Industry Group  ...  코스닥 대형주
year quarter                                                ...
2000 6                     자동차 및 부품                     소재  ...     None
     9                     자동차 및 부품                     소재  ...     None
     12                    자동차 및 부품                     소재  ...     None
2001 3                     자동차 및 부품                     소재  ...     None
     6                     자동차 및 부품                     소재  ...     None
...                             ...                    ...  ...      ...
2021 12                    자동차 및 부품                     소재  ...     None
2022 3                     자동차 및 부품                     소재  ...     None
     6                     자동차 및 부품                     소재  ...     None
     9                     자동차 및 부품                     소재  ...     None
     12                    자동차 및 부품                     소재  ...     None

Symbol       A900090 A900130 A900150 A900180  A950010 A950030 A950070 A950100  \
Symbol Name   차이나하오란    웨이포트  성융광전투자      완리 평산차업 KDR  네프로아이티    중국고섬  SBI모기지
             코스닥 대형주 코스닥 대형주 코스닥 대형주 코스닥 대형주  코스닥 대형주 코스닥 대형주 코스닥 대형주 코스닥 대형주
year quarter
2000 6          None    None    None    None     None    None    None    None
     9          None    None    None    None     None    None    None    None
     12         None    None    None    None     None    None    None    None
2001 3          None    None    None    None     None    None    None    None
     6          None    None    None    None     None    None    None    None
...              ...     ...     ...     ...      ...     ...     ...     ...
2021 12         None    None    None    None     None    None    None    None
2022 3          None    None    None    None     None    None    None    None
     6          None    None    None    None     None    None    None    None
     9          None    None    None    None     None    None    None    None
     12         None    None    None    None     None    None    None    None

Symbol       A950180
Symbol Name      SNK
             코스닥 대형주
year quarter
2000 6          None
     9          None
     12         None
2001 3          None
     6          None
...              ...
2021 12            N
2022 3             N
     6             N
     9          None
     12         None

[91 rows x 70080 columns]

In [226]:
df

Symbol             A005930                                            \
Symbol Name           삼성전자
                    총자산(원)        총자본(원)        총부채(원)        자본금(원)
year quarter
2000 3        2.496436e+13  1.401328e+13  1.095108e+13  8.776211e+11
     6        2.510607e+13  1.476346e+13  1.034261e+13  8.804522e+11
     9        2.613602e+13  1.592160e+13  1.021442e+13  8.816347e+11
     12       2.689505e+13  1.619285e+13  1.070220e+13  8.816751e+11
2001 3        2.783778e+13  1.768363e+13  1.015415e+13  8.816751e+11
...                    ...           ...           ...           ...
2021 9        2.406844e+14  1.873901e+14  5.329431e+13  8.975140e+11
     12       2.511122e+14  1.931937e+14  5.791845e+13  8.975140e+11
2022 3        2.593540e+14  1.982758e+14  6.107824e+13  8.975140e+11
     6        2.589713e+14  2.039144e+14  5.505685e+13  8.975140e+11
     9        2.610291e+14  2.070457e+14  5.398337e+13  8.975140e+11

Symbol                                                                \
Symbol Name
                   유동부채(원)      비유동부채(원)     *총차입부채(원)     *순차입부채(원)
year quarter
2000 3        6.627064e+12  4.324011e+12  5.377145e+12  4.123370e+12
     6        6.277503e+12  4.065104e+12  4.866135e+12  3.124732e+12
     9        6.601534e+12  3.612889e+12  4.575874e+12  1.684689e+12
     12       8.608449e+12  2.093751e+12  4.061056e+12  1.446021e+12
2001 3        8.129206e+12  2.024941e+12  4.349802e+12  1.931723e+12
...                    ...           ...           ...           ...
2021 9        4.959792e+13  3.696390e+12  1.122722e+13 -9.456243e+12
     12       5.306730e+13  4.851149e+12  9.804559e+12 -9.114889e+12
2022 3        5.679978e+13  4.278465e+12  1.082537e+13 -1.110678e+13
     6        5.031086e+13  4.745989e+12  9.068400e+12 -7.114918e+12
     9        4.884874e+13  5.134628e+12  4.793840e+12 -4.475861e+12

Symbol                                    ...         A950180                  \
Symbol Name                               ...             SNK
                   유동자산(원)      비유동자산(원)  ... 투자활동으로인한현금흐름(원) 재무활동으로인한현금흐름(원)
year quarter                              ...
2000 3        6.745764e+12  1.821859e+13  ...             NaN             NaN
     6        6.696682e+12  1.840938e+13  ...             NaN             NaN
     9        7.908331e+12  1.822769e+13  ...             NaN             NaN
     12       7.756441e+12  1.913861e+13  ...             NaN             NaN
2001 3        7.260043e+12  2.057774e+13  ...             NaN             NaN
...                    ...           ...  ...             ...             ...
2021 9        7.325302e+13  1.674314e+14  ...    5.935850e+08   -2.041009e+09
     12       7.355342e+13  1.775588e+14  ...   -1.027016e+10   -1.640520e+08
2022 3        8.146603e+13  1.778880e+14  ...    3.026510e+09   -2.492370e+08
     6        7.619448e+13  1.827768e+14  ...   -7.057940e+09   -3.492070e+08
     9        7.395366e+13  1.870754e+14  ...   -1.211350e+10   -3.761990e+08

Symbol                                                                    \
Symbol Name
             신종자본증권(원) 전환사채(원) 신주인수권부사채(원) 교환사채(원) 투자부동산(원) 유형자산감가상각비(원)
year quarter
2000 3             0.0     0.0         0.0     0.0      0.0          0.0
     6             0.0     0.0         0.0     0.0      0.0          0.0
     9             0.0     0.0         0.0     0.0      0.0          0.0
     12            0.0     0.0         0.0     0.0      0.0          0.0
2001 3             0.0     0.0         0.0     0.0      0.0          0.0
...                ...     ...         ...     ...      ...          ...
2021 9             0.0     0.0         0.0     0.0      0.0  174707000.0
     12            0.0     0.0         0.0     0.0      0.0  478937000.0
2022 3             0.0     0.0         0.0     0.0      0.0  548512000.0
     6             0.0     0.0         0.0     0.0      0.0  417958000.0
     9             0.0     0.0         0.0     0.0      0.0  537336000.0

Symbol
Symbol Name
             매각예정비유동자산(원)     종속기업투자(원)
year quarter
2000 3                0.0  0.000000e+00
     6                0.0  0.000000e+00
     9                0.0  0.000000e+00
     12               0.0  0.000000e+00
2001 3                0.0  0.000000e+00
...                   ...           ...
2021 9                0.0  3.606412e+10
     12               0.0  3.551352e+10
2022 3                0.0  0.000000e+00
     6                0.0  3.337995e+10
     9                0.0  2.830332e+10

[91 rows x 133152 columns]

In [228]:
reg = pd.concat([df, test2], axis=1)

In [235]:
ticker_names = reg.columns.get_level_values('Symbol Name').unique()

In [241]:
reg.loc[:,(slice(None),'삼성물산',slice(None))]

Symbol             A028260                                            \
Symbol Name           삼성물산
                    총자산(원)        총자본(원)        총부채(원)        자본금(원)
year quarter
2000 3        1.207817e+12  4.080010e+11  7.998160e+11  1.250000e+10
     6        1.494903e+12  6.782232e+11  8.166794e+11  1.250000e+10
     9        1.504570e+12  7.063610e+11  7.982090e+11  1.250000e+10
     12       1.478252e+12  6.723749e+11  8.058776e+11  1.250000e+10
2001 3        1.835511e+12  6.746820e+11  1.160828e+12  1.250000e+10
...                    ...           ...           ...           ...
2021 12       4.418092e+13  2.840802e+13  1.577289e+13  1.885145e+10
2022 3        4.209578e+13  2.622764e+13  1.586814e+13  1.885145e+10
     6        3.967385e+13  2.355446e+13  1.611939e+13  1.885145e+10
     9        3.876493e+13  2.298044e+13  1.578449e+13  1.885145e+10
     12                NaN           NaN           NaN           NaN

Symbol                                                                \
Symbol Name
                   유동부채(원)      비유동부채(원)     *총차입부채(원)     *순차입부채(원)
year quarter
2000 3        3.322850e+11  4.675310e+11  4.088130e+11  3.982560e+11
     6        3.440972e+11  4.725821e+11  3.721298e+11  3.605396e+11
     9        3.282640e+11  4.699450e+11  3.653600e+11  3.545340e+11
     12       2.103882e+11  5.954894e+11  3.788700e+11  3.694799e+11
2001 3        2.367250e+11  9.241030e+11  4.813750e+11  4.702280e+11
...                    ...           ...           ...           ...
2021 12       7.967519e+12  7.805374e+12  1.476917e+12 -1.871699e+12
2022 3        8.805868e+12  7.062271e+12  1.552334e+12  6.740992e+10
     6        9.435099e+12  6.684287e+12  4.082768e+12  1.541842e+12
     9        8.979476e+12  6.805009e+12  3.613264e+12  6.098554e+11
     12                NaN           NaN           NaN           NaN

Symbol                                    ...                     A000830  \
Symbol Name                               ...                        삼성물산
                   유동자산(원)      비유동자산(원)  ...  순매수대금(개인)(원)  순매수대금(개인)(원)
year quarter                              ...
2000 3        1.853950e+11  1.022422e+12  ...           NaN           NaN
     6        1.393024e+11  1.355600e+12  ...           NaN -3.293880e+09
     9        1.730880e+11  1.331482e+12  ...           NaN -4.930000e+08
     12       1.188120e+11  1.359441e+12  ...           NaN  1.315670e+09
2001 3        1.016060e+11  1.733905e+12  ...           NaN  5.573600e+08
...                    ...           ...  ...           ...           ...
2021 12       8.502681e+12  3.567824e+13  ... -2.123653e+10           NaN
2022 3        9.146876e+12  3.294890e+13  ... -3.534980e+09           NaN
     6        8.698201e+12  3.097565e+13  ... -2.930572e+10           NaN
     9        9.215916e+12  2.954901e+13  ...  3.612840e+09           NaN
     12                NaN           NaN  ... -6.229750e+09           NaN

Symbol             A028260    A000830      A028260    A000830        A028260  \
Symbol Name           삼성물산       삼성물산         삼성물산       삼성물산           삼성물산
                잔고금액 융자(원) 잔고금액 융자(원)   잔고금액 대주(원) 잔고금액 대주(원) KOSPI 200 편입여부
year quarter
2000 3                 NaN        NaN          NaN        NaN            NaN
     6                 NaN        NaN          NaN        NaN           None
     9                 NaN        NaN          NaN        NaN           None
     12                NaN        NaN          NaN        NaN           None
2001 3                 NaN        NaN          NaN        NaN           None
...                    ...        ...          ...        ...            ...
2021 12       5.749500e+10        NaN   14000000.0        NaN              Y
2022 3        5.113900e+10        NaN    9000000.0        NaN              Y
     6        3.932300e+10        NaN   10000000.0        NaN              Y
     9        3.841300e+10        NaN    2000000.0        NaN              Y
     12       3.601100e+10        NaN  110000000.0        NaN              Y

Symbol              A000830 A028260 A000830
Symbol Name            삼성물산    삼성물산    삼성물산
             KOSPI 200 편입여부 코스닥 대형주 코스닥 대형주
year quarter
2000 3                  NaN     NaN     NaN
     6                    Y    None       N
     9                    Y    None       N
     12                   Y    None       N
2001 3                    Y    None       N
...                     ...     ...     ...
2021 12                None       N    None
2022 3                 None       N    None
     6                 None       N    None
     9                 None       N    None
     12                None       N    None

[92 rows x 116 columns]

In [239]:
count = 0
for x in ticker_names:
    if len(reg.loc[:,(slice(None),x,slice(None))].columns) == 58:
        pass
    else:
        print(x)
        print(len(reg.loc[:,(slice(None),x,slice(None))].columns))
        count += 1

count

삼성물산
116
SK
116
미래에셋증권
116
풀무원
116
신성이엔지
116
원익피앤이
116
대동
116
금호건설
116
알루코
116
현대리바트
116
고려시멘트
116
아이티센
116
핸디소프트
116
하나은행
116
두산건설
116
광주은행
116
경남은행
116
국민은행
116

18

In [243]:
reg.to_pickle('Final_Reg.pkl')

# 결과 불러오기

In [244]:
df = pd.read_pickle("Final_Reg.pkl")

# 이렇게 Slicing

In [246]:
df.loc[:, (slice(None), '삼성전자', slice(None))]

Symbol             A005930                                            \
Symbol Name           삼성전자
                    총자산(원)        총자본(원)        총부채(원)        자본금(원)
year quarter
2000 3        2.496436e+13  1.401328e+13  1.095108e+13  8.776211e+11
     6        2.510607e+13  1.476346e+13  1.034261e+13  8.804522e+11
     9        2.613602e+13  1.592160e+13  1.021442e+13  8.816347e+11
     12       2.689505e+13  1.619285e+13  1.070220e+13  8.816751e+11
2001 3        2.783778e+13  1.768363e+13  1.015415e+13  8.816751e+11
...                    ...           ...           ...           ...
2021 12       2.511122e+14  1.931937e+14  5.791845e+13  8.975140e+11
2022 3        2.593540e+14  1.982758e+14  6.107824e+13  8.975140e+11
     6        2.589713e+14  2.039144e+14  5.505685e+13  8.975140e+11
     9        2.610291e+14  2.070457e+14  5.398337e+13  8.975140e+11
     12                NaN           NaN           NaN           NaN

Symbol                                                                \
Symbol Name
                   유동부채(원)      비유동부채(원)     *총차입부채(원)     *순차입부채(원)
year quarter
2000 3        6.627064e+12  4.324011e+12  5.377145e+12  4.123370e+12
     6        6.277503e+12  4.065104e+12  4.866135e+12  3.124732e+12
     9        6.601534e+12  3.612889e+12  4.575874e+12  1.684689e+12
     12       8.608449e+12  2.093751e+12  4.061056e+12  1.446021e+12
2001 3        8.129206e+12  2.024941e+12  4.349802e+12  1.931723e+12
...                    ...           ...           ...           ...
2021 12       5.306730e+13  4.851149e+12  9.804559e+12 -9.114889e+12
2022 3        5.679978e+13  4.278465e+12  1.082537e+13 -1.110678e+13
     6        5.031086e+13  4.745989e+12  9.068400e+12 -7.114918e+12
     9        4.884874e+13  5.134628e+12  4.793840e+12 -4.475861e+12
     12                NaN           NaN           NaN           NaN

Symbol                                    ...                                \
Symbol Name                               ...
                   유동자산(원)      비유동자산(원)  ...       거래대금(원) 상장및상장예정주식수(보통주)
year quarter                              ...
2000 3        6.745764e+12  1.821859e+13  ...           NaN             NaN
     6        6.696682e+12  1.840938e+13  ...  2.611347e+11    1.509012e+08
     9        7.908331e+12  1.822769e+13  ...  2.317735e+11    1.512319e+08
     12       7.756441e+12  1.913861e+13  ...  1.942091e+11    1.512399e+08
2001 3        7.260043e+12  2.057774e+13  ...  1.238044e+11    1.512399e+08
...                    ...           ...  ...           ...             ...
2021 12       7.355342e+13  1.775588e+14  ...  1.120743e+12    5.969783e+09
2022 3        8.146603e+13  1.778880e+14  ...  8.732126e+11    5.969783e+09
     6        7.619448e+13  1.827768e+14  ...  1.082799e+12    5.969783e+09
     9        7.395366e+13  1.870754e+14  ...  1.187344e+12    5.969783e+09
     12                NaN           NaN  ...  1.218355e+12    5.969783e+09

Symbol                                                                   \
Symbol Name
             상장및상장예정주식수(우선주) 순매수대금(기관계)(원) 순매수대금(외국인계)(원)  순매수대금(개인)(원)
year quarter
2000 3                   NaN           NaN            NaN           NaN
     6            23893427.0 -1.684060e+10  -6.732003e+10  7.705425e+10
     9            23893427.0 -7.367350e+09  -2.369369e+10  2.769976e+10
     12           23893427.0 -2.384329e+10   7.884840e+09 -1.177294e+10
2001 3            23893427.0 -1.008720e+09  -9.226480e+09  1.119503e+10
...                      ...           ...            ...           ...
2021 12          822886700.0 -2.355468e+11   4.711275e+10  1.868082e+11
2022 3           822886700.0  1.186300e+08  -2.243323e+11  2.201073e+11
     6           822886700.0 -5.676019e+10  -1.709717e+11  2.288256e+11
     9           822886700.0  3.001964e+10   6.857518e+10 -9.878368e+10
     12          822886700.0 -1.378300e+11   3.427397e+11 -1.881547e+11

Symbol
Symbol Name
                잔고금액 융자(원)    잔고금액 대주(원) KOSPI 200 편입여부 코스닥 대형주
year quarter
2000 3                 NaN           NaN            NaN     NaN
     6                 NaN           NaN              Y       N
     9                 NaN           NaN              Y       N
     12                NaN           NaN              Y       N
2001 3                 NaN           NaN              Y       N
...                    ...           ...            ...     ...
2021 12       5.407110e+11  1.931000e+09              Y       N
2022 3        6.275740e+11  6.870000e+08              Y       N
     6        6.815550e+11  4.390000e+08              Y       N
     9        6.351040e+11  2.100000e+08              Y       N
     12       4.508710e+11  1.424000e+09              Y       N

[92 rows x 58 columns]

# 티커명이 바뀐 경우가 있음

In [256]:
df.loc[:, (slice(None), '삼성물산', slice(None))].columns.get_level_values('Symbol').unique()

Index(['A028260', 'A000830'], dtype='object', name='Symbol')

In [259]:
overlap = df.loc[:, (slice(None), '삼성물산', slice(None))].columns.get_level_values('Symbol').unique()

In [260]:
df.loc[:, (overlap[0], '삼성물산', slice(None))]

Symbol             A028260                                            \
Symbol Name           삼성물산
                    총자산(원)        총자본(원)        총부채(원)        자본금(원)
year quarter
2000 3        1.207817e+12  4.080010e+11  7.998160e+11  1.250000e+10
     6        1.494903e+12  6.782232e+11  8.166794e+11  1.250000e+10
     9        1.504570e+12  7.063610e+11  7.982090e+11  1.250000e+10
     12       1.478252e+12  6.723749e+11  8.058776e+11  1.250000e+10
2001 3        1.835511e+12  6.746820e+11  1.160828e+12  1.250000e+10
...                    ...           ...           ...           ...
2021 12       4.418092e+13  2.840802e+13  1.577289e+13  1.885145e+10
2022 3        4.209578e+13  2.622764e+13  1.586814e+13  1.885145e+10
     6        3.967385e+13  2.355446e+13  1.611939e+13  1.885145e+10
     9        3.876493e+13  2.298044e+13  1.578449e+13  1.885145e+10
     12                NaN           NaN           NaN           NaN

Symbol                                                                \
Symbol Name
                   유동부채(원)      비유동부채(원)     *총차입부채(원)     *순차입부채(원)
year quarter
2000 3        3.322850e+11  4.675310e+11  4.088130e+11  3.982560e+11
     6        3.440972e+11  4.725821e+11  3.721298e+11  3.605396e+11
     9        3.282640e+11  4.699450e+11  3.653600e+11  3.545340e+11
     12       2.103882e+11  5.954894e+11  3.788700e+11  3.694799e+11
2001 3        2.367250e+11  9.241030e+11  4.813750e+11  4.702280e+11
...                    ...           ...           ...           ...
2021 12       7.967519e+12  7.805374e+12  1.476917e+12 -1.871699e+12
2022 3        8.805868e+12  7.062271e+12  1.552334e+12  6.740992e+10
     6        9.435099e+12  6.684287e+12  4.082768e+12  1.541842e+12
     9        8.979476e+12  6.805009e+12  3.613264e+12  6.098554e+11
     12                NaN           NaN           NaN           NaN

Symbol                                    ...                                \
Symbol Name                               ...
                   유동자산(원)      비유동자산(원)  ...       거래대금(원) 상장및상장예정주식수(보통주)
year quarter                              ...
2000 3        1.853950e+11  1.022422e+12  ...           NaN             NaN
     6        1.393024e+11  1.355600e+12  ...           NaN             0.0
     9        1.730880e+11  1.331482e+12  ...           NaN             0.0
     12       1.188120e+11  1.359441e+12  ...           NaN             0.0
2001 3        1.016060e+11  1.733905e+12  ...           NaN             0.0
...                    ...           ...  ...           ...             ...
2021 12       8.502681e+12  3.567824e+13  ...  9.265365e+10     186887081.0
2022 3        9.146876e+12  3.294890e+13  ...  2.655521e+10     186887081.0
     6        8.698201e+12  3.097565e+13  ...  1.075746e+11     186887081.0
     9        9.215916e+12  2.954901e+13  ...  3.387402e+10     186887081.0
     12                NaN           NaN  ...  3.920259e+10     186887081.0

Symbol                                                                   \
Symbol Name
             상장및상장예정주식수(우선주) 순매수대금(기관계)(원) 순매수대금(외국인계)(원)  순매수대금(개인)(원)
year quarter
2000 3                   NaN           NaN            NaN           NaN
     6                   0.0           NaN            NaN           NaN
     9                   0.0           NaN            NaN           NaN
     12                  0.0           NaN            NaN           NaN
2001 3                   0.0           NaN            NaN           NaN
...                      ...           ...            ...           ...
2021 12            1627425.0  5.508830e+09   1.562785e+10 -2.123653e+10
2022 3             1627425.0  6.183300e+08   2.954310e+09 -3.534980e+09
     6             1627425.0  2.399922e+10   5.161260e+09 -2.930572e+10
     9             1627425.0 -8.484900e+08  -2.761130e+09  3.612840e+09
     12            1627425.0 -4.949690e+09   1.157070e+10 -6.229750e+09

Symbol
Symbol Name
                잔고금액 융자(원)   잔고금액 대주(원) KOSPI 200 편입여부 코스닥 대형주
year quarter
2000 3                 NaN          NaN            NaN     NaN
     6                 NaN          NaN            NaN     NaN
     9                 NaN          NaN            NaN     NaN
     12                NaN          NaN            NaN     NaN
2001 3                 NaN          NaN            NaN     NaN
...                    ...          ...            ...     ...
2021 12       5.749500e+10   14000000.0              Y       N
2022 3        5.113900e+10    9000000.0              Y       N
     6        3.932300e+10   10000000.0              Y       N
     9        3.841300e+10    2000000.0              Y       N
     12       3.601100e+10  110000000.0              Y       N

[92 rows x 58 columns]

In [261]:
df.loc[:, (overlap[1], '삼성물산', slice(None))]

Symbol             A000830                                            \
Symbol Name           삼성물산
                    총자산(원)        총자본(원)        총부채(원)        자본금(원)
year quarter
2000 3        8.913979e+12  3.569736e+12  5.344243e+12  8.004210e+11
     6        8.960416e+12  3.726638e+12  5.233778e+12  8.004209e+11
     9        7.738923e+12  2.697067e+12  5.041856e+12  8.004210e+11
     12       7.321044e+12  2.512359e+12  4.808685e+12  8.004209e+11
2001 3        7.695971e+12  2.855981e+12  4.839990e+12  8.004209e+11
...                    ...           ...           ...           ...
2021 12                NaN           NaN           NaN           NaN
2022 3                 NaN           NaN           NaN           NaN
     6                 NaN           NaN           NaN           NaN
     9                 NaN           NaN           NaN           NaN
     12                NaN           NaN           NaN           NaN

Symbol                                                                \
Symbol Name
                   유동부채(원)      비유동부채(원)     *총차입부채(원)     *순차입부채(원)
year quarter
2000 3        3.597486e+12  1.746757e+12  2.964768e+12  2.588727e+12
     6        3.227194e+12  2.006585e+12  2.664184e+12  2.374190e+12
     9        3.411786e+12  1.630070e+12  2.813868e+12  2.173775e+12
     12       3.656899e+12  1.151786e+12  2.193294e+12  1.662472e+12
2001 3        3.678726e+12  1.161264e+12  2.212152e+12  1.752318e+12
...                    ...           ...           ...           ...
2021 12                NaN           NaN           NaN           NaN
2022 3                 NaN           NaN           NaN           NaN
     6                 NaN           NaN           NaN           NaN
     9                 NaN           NaN           NaN           NaN
     12                NaN           NaN           NaN           NaN

Symbol                                    ...                                \
Symbol Name                               ...
                   유동자산(원)      비유동자산(원)  ...       거래대금(원) 상장및상장예정주식수(보통주)
year quarter                              ...
2000 3        3.949023e+12  4.964956e+12  ...           NaN             NaN
     6        3.746336e+12  5.214080e+12  ...  1.615603e+10             0.0
     9        3.590855e+12  4.148068e+12  ...  1.100860e+10             0.0
     12       3.459565e+12  3.861479e+12  ...  6.385499e+09             0.0
2001 3        3.523578e+12  4.172394e+12  ...  4.796702e+09             0.0
...                    ...           ...  ...           ...             ...
2021 12                NaN           NaN  ...           NaN             0.0
2022 3                 NaN           NaN  ...           NaN             0.0
     6                 NaN           NaN  ...           NaN             0.0
     9                 NaN           NaN  ...           NaN             0.0
     12                NaN           NaN  ...           NaN             0.0

Symbol                                                                   \
Symbol Name
             상장및상장예정주식수(우선주) 순매수대금(기관계)(원) 순매수대금(외국인계)(원)  순매수대금(개인)(원)
year quarter
2000 3                   NaN           NaN            NaN           NaN
     6                   0.0  2.024610e+09    684760000.0 -3.293880e+09
     9                   0.0  4.285800e+08     -1280000.0 -4.930000e+08
     12                  0.0 -5.217500e+08    187610000.0  1.315670e+09
2001 3                   0.0 -5.841200e+08      2580000.0  5.573600e+08
...                      ...           ...            ...           ...
2021 12                  0.0           NaN            NaN           NaN
2022 3                   0.0           NaN            NaN           NaN
     6                   0.0           NaN            NaN           NaN
     9                   0.0           NaN            NaN           NaN
     12                  0.0           NaN            NaN           NaN

Symbol
Symbol Name
             잔고금액 융자(원) 잔고금액 대주(원) KOSPI 200 편입여부 코스닥 대형주
year quarter
2000 3              NaN        NaN            NaN     NaN
     6              NaN        NaN              Y       N
     9              NaN        NaN              Y       N
     12             NaN        NaN              Y       N
2001 3              NaN        NaN              Y       N
...                 ...        ...            ...     ...
2021 12             NaN        NaN           None    None
2022 3              NaN        NaN           None    None
     6              NaN        NaN           None    None
     9              NaN        NaN           None    None
     12             NaN        NaN           None    None

[92 rows x 58 columns]